### ISSUE TITLE
Every time I deploy from Azure AI Studio, I get an error message「An error occurred. .....」

### ISSUE THREAD

**Issue by sinjorjob** [microsoft/sample-app-aoai-chatGPT#579] opened 2024-02-03 22:32 UTC
After deploying with New Web apps from Azure OpenAI Studio, the following error occurs every time when I ask a question in the chat from the web app screen.
「An error occurred. Please try again. If the problem persists, please contact the site administrator.」

When i check my browser's console error,  see the following error:

> Chat.tsx:222 SyntaxError: Unterminated string in JSON at position 4084 (line 1 column 4085)
    at JSON.parse (<anonymous>)
    at Chat.tsx:205:47
    at Array.forEach (<anonymous>)
    at W (Chat.tsx:202:29)

Looking at the error message and code, it looks like JSON.parse() is failing.
 This seems like an error caused by an incorrect string in JSON format.

I'll also attach a screenshot of the error screen.
Please check it.
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/34405452/4b897f76-4971-4b2d-8ac7-3c0785c9408a)

**Comment by junan-trustarc** [comment] 2024-02-06 19:15
Same happening for me, it looks like individual message in async from BE doesn't return completed json sometimes and UI is parsing by JSON and throw error.

**Comment by VikashLalit** [comment] 2024-02-07 00:25
@sarah-widder It will be a great help if you can guide us for above error...I am also getting same error and i see many other people are also facing the same

**Comment by sarah-widder** [comment] 2024-02-07 00:27
Can you share more details of the settings for apps that are hitting this issue?

For example: chat history enabled/disabled, using data or not, which data source type, which AOAI model type and version. Also, enable backend logging and see if you can share a more detailed log from the backend of what is being returned.

**Comment by junan-trustarc** [comment] 2024-02-07 17:34
@sarah-widder 
1. chat history enabled
2. using own data (both same issue either ai search index with 1024 default chunk or 64k chunk)
3. same issue either GPT-4 or GPT-4-turbo
4. open ai api version = 2023-12-01-preview (latest from main branch)
5. same issue either main branch from this repo or forked one (both are having latest sync).

One thing I notified, I can't reproduce in locally as it is working fine (it is same properties between local and azure webapp).
Only happening on webapp after it is deployed by AI Studio.

**Comment by junan-trustarc** [comment] 2024-02-07 19:11
and this is happening after https://github.com/microsoft/sample-app-aoai-chatGPT/pull/460

**Comment by sarah-widder** [comment] 2024-02-07 20:00
Thanks @junan-trustarc for the additional details! We're working to reproduce and fix this.

**Comment by sarah-widder** [comment] 2024-02-08 05:32
Hi folks - I have a possible fix in #599. I haven't been able to reproduce this consistently on my side, if you would be able to pull in the changes and give it a try in your app, that would be very helpful to validate that this addresses the issue. I hit this very rarely before the fix and not at all after the fix.

**Comment by junan-trustarc** [comment] 2024-02-08 06:46
@sarah-widder  I am still getting it with your branch.
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/134445960/4aefbac1-2f5a-4422-b7aa-5873a82e6829)

**Comment by sarah-widder** [comment] 2024-02-08 16:08
Hi @junan-trustarc thanks for giving it a try. I made a small update to my branch to fix the exception handling condition - do you mind giving it another try?

**Comment by junan-trustarc** [comment] 2024-02-08 16:30
Hi @sarah-widder looks good now.

Could you merge to main? thank you so much !

One suggestion, there is timing gap between "generating answer..."  and actual answer box coming. as it always show blank if citation is big and next response is late.

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/134445960/459f1ea6-87a2-444b-b48c-97fcabbd6280)
We can still show loading until first assistant message is coming since first message is always "tool" with citation and next is "assistant"

**Comment by sarah-widder** [comment] 2024-02-08 16:32
Thanks for testing and for the callout @junan-trustarc I've noticed that issue too. The stream is a little different when using data vs. not using data (no citations in that case) so we'll do some testing and work on a fix like what you propose in a separate PR.

**Comment by sarah-widder** [comment] 2024-02-08 16:40
#599 is merged. If anyone is still hitting the issue, please pull in the latest from main either to your local development environment, or by using the "Sync" button in the Deployment Center on the app service resource that was deployed from the chat playground. Closing the issue.

**Closed by sarah-widder** 2024-02-08 16:40 UTC
