### ISSUE TITLE
please enable hit highlighting!

### ISSUE THREAD

**Issue by HARISHKUMAR1112001** [microsoft/sample-app-aoai-chatGPT#40] opened 2023-06-18 07:06 UTC
After creating index and uploading documents to it , when I am using it with chat app it was giving :"please enable hit highlighting!"

**Comment by ashatabak786** [comment] 2023-06-20 21:29
Thanks for sharing! I have a few questions about the setup:
 - Can you please share what queries are you running? Does it fail for few queries or all queries?
 - Does it work with the studio?
 - Can you check if the index is created in the search instance.

This information would help us root cause the issue.

**Comment by tommywu052** [comment] 2023-06-21 05:07
same issue here, it works well on the AI studio.  but failed on the deployed web app, which show the error: 
code500
message
"Please enable hit highlighting!"
Where should I check the query ? I assume it was generated by by app.

**Comment by ashatabak786** [comment] 2023-06-21 19:23
Got it. 

As in what do you put in the search box when you face this error. Or do you get this error for all questions you put in the search box?

**Comment by sarah-widder** [comment] 2023-07-25 18:29
Hi @HARISHKUMAR1112001 and @tommywu052 we rolled out an update a couple of weeks ago that should fix this issue. I'm closing the thread. Please feel free to reopen if you hit this error again.

**Closed by sarah-widder** 2023-07-25 18:29 UTC
Labels: bug

**Comment by Harish-Tricon** [comment] 2023-07-26 01:25
> out

@sarah-widder 👍

**Comment by HARISHKUMAR1112001** [comment] 2023-07-26 01:28
> Hi @HARISHKUMAR1112001 and @tommywu052 we rolled out an update a couple of weeks ago that should fix this issue. I'm closing the thread. Please feel free to reopen if you hit this error again.

@sarah-widder, thanks 👍
